### ISSUE TITLE
yarn test Cannot find module 'webpack/lib/Watching'

### ISSUE THREAD

**Issue by AlnoorKhan** [FrontendMasters/api-design-node-v2#6]
Error: Cannot find module 'webpack/lib/Watching'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/pathToRepo/node_modules/mocha-webpack/lib/webpack/compiler/createWatchCompiler.js:21:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by Hendrixer** [comment]
must be downloading a newer version on `webapck` that when the course was created. I'll lock in the versions. You can do so now but only installing the version in the package.json

**Comment by Marcus20** [comment]
@AlnoorKhan You need to have the following in your package.json devDependencies for the test suite to work. 

`"mocha-webpack": "^2.0.0-beta.0",` 
`"webpack": "^4.0.0-beta.2",`

and then run

`npm i`

**Comment by AlnoorKhan** [comment]
@Marcus20 Thanks that worked.
